import ScrollingText from "@/components/scrollingtext/scrollingtext";
import "./globals.css";
import type { Metadata } from "next";
import { montserrat } from "@/components/fonts/fonts";
import Header from "@/components/header/header";
import OptionsStrip from "@/components/optionsstrip/optionsstrip";
import Footer from "@/components/footer/footer";
import { ExportSessionProvider } from "@/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ExportSessionProvider>
      <html lang="en">
        <body className={montserrat.className}>
          <ScrollingText></ScrollingText>
          <OptionsStrip></OptionsStrip>
          <Header></Header>
          {children}
          <Footer></Footer>
        </body>
      </html>
    </ExportSessionProvider>
  );
}
