import Cookies from "@/src/components/cookies/cookies";
import Navbar from "@/src/components/navbar/navbar";
import Providers from "@/src/utils/providers";
import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box overflow={"hidden"}>
            <Suspense>
              <Navbar></Navbar>
            </Suspense>
            {children}
            <Suspense>
              <Cookies></Cookies>
            </Suspense>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
