import ServersSideNav from "@/utils/components/serverssidenav/serverssidenav";
import { Box, Container, Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Container>
      <Flex>
        <ServersSideNav></ServersSideNav>
        <Box flexGrow={1} ml={8}>
          {children}
        </Box>
      </Flex>
    </Container>
  );
}
