import type { Metadata } from "next";
import "./globals.css";
import { rubik } from "./fonts/fonts";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
