import Framer from "@/utils/components/framer/framer";
import { Box, Paper } from "@mui/material";
import { grey } from "@mui/material/colors";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginAndRegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box
      minHeight={"100dvh"}
      display={"flex"}
      alignItems={"center"}
      justifyContent={"center"}
    >
      <Framer
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ type: "spring", stiffness: 200, damping: 40 }}
      >
        <Paper
          elevation={8}
          sx={{ backgroundColor: "custom.light", color: grey[50], p: 3 }}
        >
          {children}
        </Paper>
      </Framer>
    </Box>
  );
}
