services:
  next:
    build:
      context: ../../docker/dev/next
    ports:
      - ${APP_ENTRYPORT}:3000
      - ${PRISMA_STUDIO_ENTRYPORT}:5555
    volumes:
      - ../../../next:/app
    command: bash -c "npm install && npm run dev"
  db:
    build:
      context: ../../docker/dev/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_ENTRYPORT}:5433
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5433
