version: "3"
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./volumes/jenkins/data:/var/jenkins_home
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./volumes/prometheus/config:/etc/prometheus
      - ./volumes/prometheus/data:/prometheus
  grafana:
    image: grafana/grafana
    user: 1000:1000
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
