import News from "@/components/news/news";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import Cookies from "@/components/cookies/cookies";
import { Providers } from "@/components/providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Providers>
          <News></News>
          <Header></Header>
          {children}
          <Footer></Footer>
          <Cookies></Cookies>
        </Providers>
      </body>
    </html>
  );
}
