import Navigation from "@/utils/components/navigation/navigation";
import Providers from "@/utils/providers";
import { montserrat } from "@/utils/theme";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Providers>
          <Navigation></Navigation>
          {children}
        </Providers>
      </body>
    </html>
  );
}
